on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A test to get PR number
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Find PR
        uses: ./
        id: hello
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the pr number
        run: echo "The time was ${{ steps.hello.outputs.pr }}"
